apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: website-container
          image: prathamesh1115/website:latest
          ports:
            - containerPort: 80


